config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_i3blocks:
    dst: ~/.i3/i3blocks
    src: i3/i3blocks
  d_polybar:
    dst: ~/.config/polybar
    src: polybar
  f_compton.conf:
    dst: ~/.i3/compton.conf
    src: i3/compton.conf
  f_dunst:
    dst: ~/.i3/dunst
    src: i3/dunst
  f_i3_config:
    dst: ~/.i3/config
    src: i3/config
  f_i3blocks.conf:
    dst: ~/.i3/i3blocks.conf
    src: i3/i3blocks.conf
  f_profile:
    dst: ~/.profile
    src: profile
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: .tmux.conf
  f_zshrc:
    dst: ~/dotfiles/.zshrc
    src: .zshrc
profiles:
  imarkov:
  - f_i3_config
  - f_zshrc
  - f_profile
  - f_tmux.conf
  - f_compton.conf
  - f_dunst
  - f_i3blocks.conf
  - d_i3blocks
  - d_polybar
