#!/bin/python
# -*- coding: utf-8 -*-

import requests

CITY = "3067696"
API_KEY = "5394db3702b5003e534c93da64992fb3"
UNITS = "Metric"
UNIT_KEY = "C"

REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?id={}&appid={}&units={}".format(CITY, API_KEY, UNITS))
if REQ.status_code == 200:
    CURRENT = REQ.json()["weather"][0]["description"].capitalize()
    TEMP = int(float(REQ.json()["main"]["temp"]))
    print("{}, {} °{}".format(CURRENT, TEMP, UNIT_KEY))
else:
    print("The sky is the color of television turned to a dead channel")