#!/bin/bash
SP_VERSION="0.1"
SP_DEST="org.mpris.MediaPlayer2.spotify"
SP_PATH="/org/mpris/MediaPlayer2"
SP_MEMB="org.mpris.MediaPlayer2.Player"

SPOTIFY_METADATA="$(dbus-send                                                 \
 --print-reply                                  `# We need the reply.`       \
 --dest=$SP_DEST                                                             \
 $SP_PATH                                                                    \
 org.freedesktop.DBus.Properties.Get                                         \
 string:"$SP_MEMB" string:'Metadata'                                         \
 | grep -Ev "^method"                           `# Ignore the first line.`   \
 | grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' `# Filter interesting fiels.`\
 | sed -E '2~2 a|'                              `# Mark odd fields.`         \
 | tr -d '\n'                                   `# Remove all newlines.`     \
 | sed -E 's/\|/\n/g'                           `# Restore newlines.`        \
 | sed -E 's/(xesam:)|(mpris:)//'               `# Remove ns prefixes.`      \
 | sed -E 's/^"//'                              `# Strip leading...`         \
 | sed -E 's/"$//'                              `# ...and trailing quotes.`  \
 | sed -E 's/\"+/|/'                             `# Regard "" as seperator.`  \
 | sed -E 's/ +/ /g'                            `# Merge consecutive spaces.`\
)"

SPOTIFY_STATUS="$(dbus-send 						\
 --print-reply								\
 --dest=$SP_DEST							\
 $SP_PATH								\
 org.freedesktop.DBus.Properties.Get 					\
 string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'		\
 | grep -Po '\".*?\"'							\
 | tr -d '\"'								\
)"

TrackArtist=$(echo "$SPOTIFY_METADATA" | sed -n 's/artist|//p')
TrackTitle=$(echo "$SPOTIFY_METADATA" | sed -n 's/title|//p')

case $SPOTIFY_STATUS in
	"Playing") COLOR="#81b71a" ;;
	*) COLOR="#868686" ;;
esac


echo "<span foreground=\"$COLOR\"></span><span foreground=\"#13191c\">.</span><span foreground=\"$COLOR\">$TrackArtist - $TrackTitle</span>"

PlayPause="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"

case $BLOCK_BUTTON in
	1) i3-msg [class="Spotify"] focus ;; #> /dev/null ;;
	2) $PlayPause > /dev/null ;;
	3) $PlayPause > /dev/null ;;
esac
